import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { useState, useEffect } from 'react'
import Canvas from '../components/Canvas';
import TextField from '@mui/material/TextField'
import { AppBar, IconButton, Toolbar , Typography} from '@mui/material';
import MenuIcon from '@mui/material/Menu'
export default function Home() {
  const [threadLink, setThreadLink] = useState('');
  const [apiId, setApiId] = useState('');
  function handleChange(e) {
    setThreadLink(e.target.value);
    console.log(e.target.value);
  }
  return (
    <div className={styles.container}>
      <Head>
        <title>Tweet To Quote</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <AppBar position="static">
        <Toolbar 
          variant="dense" 
          align-items="center" 
          style={{
            display:"flex",
            alignContent: "center",
            justifyContent: "center",
            alignItems: "center",
            width:"100%",
          }}>
          <IconButton edge="start" color="inherit" aria-label="menu" sx={{ mr: 2 }}>
          </IconButton>
          <MenuIcon/>
          <Typography variant="h6" color="inherit" align-items="center" component="div">
            Tweet to Quote
          </Typography>
          </Toolbar>
      </AppBar>

      <main className={styles.main}>
      {/* <canvas id="myCanvas" width="200" height="100" style="border:1px solid #000000;">
      </canvas> */}

      <TextField id="outlined-basic" label="Enter Tweet Link" variant="outlined" key ="textbox" value={threadLink} onChange={(e)=>{setThreadLink(e.target.value)}}/>
      <br/>
      <Canvas text ={threadLink}/>
      </main>

      
    </div>
  )
}
